### ISSUE TITLE
Reveal script test folder or File does not exist?

### ISSUE THREAD

**Issue by crypticsymmetry** [kf106/ipfs-submarine#1]
Hi im runnig through the test. and i keep getting this error when running reveal script. i have tried multiple addresses for the "test" folder/file. it doesnt seem to be able to find the location? any ideas on why this is?

`ipfs-submarine-main$ ./reveal.sh test/0.json
IPFS installed: proceeding
File does not exist`

Thanks.

**Comment by arpitkarnatak** [comment]
I got this same issue. How was this fixed?

**Comment by kf106** [comment]
There were some problems in the scripts with relative paths that I have fixed. It could be due to those.
